name: ExploitPatcher
version: ${project.version}
main: com.larskrs.plugins.exploitpatcher.ExploitPatcher
authors: [ Larskrs ]
description: A plugin to disable certain features to prevent exploits.
commands:
  exploitpatcher:
    aliases:
      - ep
      - eploitp
      - epatcher
    description: the main command for ExploitPathcer
    permission: exploitPatcher.edit
permissions:
  exploitPatcher.bypass.blocked.blocks:
    description: Allows player to bypass blocked blocks.
    default: op

  exploitPatcher.edit.entities:
    description: Allows player to edit the blocked entities.
    default: op
    children:
      - exploitPatcher.edit
  exploitPatcher.edit.blocks:
    description: Allows player to edit the blocked blocks.
    default: op
    children:
      - exploitPatcher.edit
  exploitPatcher.edit:
    description: Allows player to edit.
    default: op

