name: ExploitPatcher
version: ${project.version}
main: com.larskrs.plugins.exploitpatcher.ExploitPatcher
authors: [ Larskrs ]
description: A plugin to disable certain features to prevent exploits.
commands:
  exploitpatcher:
    aliases:
      - ep
      - eploitp
      - epatcher
    description: the main command for ExploitPathcer
  test:

